---
title: "R Notebook"
output: html_notebook
---
```{r}
library(StereoMorph)
library(Momocs)
library(ggplot2)
library(geomorph)
library(readr)
library(purrr)
library(listviewer)
library(tibble)
```

```{r}
(localities<-read_csv("Marks_Mox - Sheet1.csv"))
```

```{r}
files<-paste0("Mox_images/shapes/TU198404_",1:6,"_L.txt")
a<-readShapes(files,fields=c("landmarks.scaled","curves.scaled"))
```

```{r}
str(a,levels=1)
```

```{r}
lm<-a$landmarks.scaled
```

```{r}
curv<-a$curves.scaled
```




```{r}

for (i in 1:6) {

  lm[,,i]<-rbind(lm[,,i],pointsAtEvenSpacing(curv[[i]]["body_post"],n=10), 
                         pointsAtEvenSpacing(curv[[i]]["body_ant"],n=10),
                         pointsAtEvenSpacing(curv[[i]]["opercle"],n=5))
}
```


```{r}
ggplot(as.data.frame(lm1),aes(V1,V2))+
  geom_point()
```
```{r}
gpa<-gpagen(a$landmarks.scaled)
gpa
```
```{r}
plotAllSpecimens(gpa$coords,mean=F)
```
```{r}
jsonedit(a,mode="view")
```



```{r}
map(flatten(a$curves.scaled),~pointsAtEvenSpacing(.x,n = 20),"body_ant")
```
```{r}
dd<-array_tree(a$landmarks.scaled,margin = 3)
landmarkListToMatrix(dd)
```
```{r}
landmarkMatrixToList(a$landmarks.scaled,k=2)
```


